# Generated by Django 3.2.8 on 2021-10-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Post',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.post'),
            preserve_default=False,
        ),
    ]
