# Generated by Django 3.2.8 on 2021-10-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211017_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
