# Generated by Django 3.2.8 on 2021-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.IntegerField(default=0),
        ),
    ]
